export const orders = [
  {
    id: 101,
    customer: "Maria",
    category: "Entree",
    item: "Blackened Salmon",
    price: 18.5,
    quantity: 2,
    status: "completed",
  },
  {
    id: 102,
    customer: "James",
    category: "Appetizer",
    item: "Crispy Calamari",
    price: 11.5,
    quantity: 1,
    status: "completed",
  },
  {
    id: 103,
    customer: "Maria",
    category: "Dessert",
    item: "Key Lime Pie",
    price: 7.5,
    quantity: 2,
    status: "pending",
  },
  {
    id: 104,
    customer: "Robert",
    category: "Entree",
    item: "Shrimp & Grits",
    price: 16.75,
    quantity: 1,
    status: "completed",
  },
  {
    id: 105,
    customer: "Angela",
    category: "Entree",
    item: "Grilled Mahi-Mahi",
    price: 19.25,
    quantity: 2,
    status: "completed",
  },
  {
    id: 106,
    customer: "James",
    category: "Dessert",
    item: "Coconut Panna Cotta",
    price: 8.25,
    quantity: 1,
    status: "pending",
  },
  {
    id: 107,
    customer: "Maria",
    category: "Appetizer",
    item: "Crab Cakes",
    price: 13.5,
    quantity: 1,
    status: "completed",
  },
  {
    id: 108,
    customer: "Robert",
    category: "Entree",
    item: "Lobster Ravioli",
    price: 21.0,
    quantity: 1,
    status: "completed",
  },
  {
    id: 109,
    customer: "Angela",
    category: "Dessert",
    item: "Chocolate Sea Salt Tart",
    price: 8.75,
    quantity: 3,
    status: "completed",
  },
  {
    id: 110,
    customer: "David",
    category: "Appetizer",
    item: "Garlic Butter Shrimp",
    price: 12.25,
    quantity: 2,
    status: "pending",
  },
  {
    id: 111,
    customer: "Maria",
    category: "Entree",
    item: "Seafood Pasta",
    price: 17.5,
    quantity: 1,
    status: "completed",
  },
  {
    id: 112,
    customer: "David",
    category: "Entree",
    item: "Fish & Chips",
    price: 15.25,
    quantity: 1,
    status: "completed",
  },
];
